### ISSUE TITLE
Support for Swift

### ISSUE THREAD

**Issue by MartinE-batanga** [urbanairship/ua-ios-pod#11]
I can't find a way to make this pod work with a Swift project. If this is possible, it would be great to have a sample showing how to do it.

**Comment by grosch** [comment]
What's your issue?  It just worked for me until I include the use_frameworks! option in my Podfile as I tried to start using Alamofire.

**Comment by MartinE-batanga** [comment]
I think my problem was that my project has support for iOS 7.0 (I don't recall all details. I'll try to reproduce the issue again later if needed).
I now got UrbanAirship working, but I had to include the libUAirship-6.0.1.a library and write my own bridging header. Not exactly ideal.

**Comment by crow** [comment]
The only way to support swift projects is via bridging header/static library. The use_frameworks! option is not currently supported.
