### ISSUE TITLE
Localizations are broken

### ISSUE THREAD

**Issue by krzat** [urbanairship/ua-ios-pod#13]
Resources doesn't seem to be configured properly, and the only UAInteractiveNotifications.strings file that is copied to the .app directory is the spanish one.

To reproduce:
1. Make new Xcode app.
2. run pod init, add pod 'UrbanAirship-iOS-SDK', '~> 6.0', and run pod install
3. build for device
4. When build is ready, open Products/<your app name>.app
5. select "Show Package Contents" on the .app

Observed: UAInteractiveNotifications.strings is in the root directory of the .app, the spanish version
Expected: language files should be in directories like en.lproj, es.lproj, etc.

**Comment by crow** [comment]
Release 6.1.0 will resolve this issue by installing the necessary lproj directories when a user specifies the UI dependencies 'PushUI', 'RichPushUI' or 'All'. Thanks for the clear description and reproduction steps.
