### ISSUE TITLE
Cocoapod misconfigured with Localization strings file

### ISSUE THREAD

**Issue by mikerz** [urbanairship/ua-ios-pod#14]
Possibly related to https://github.com/urbanairship/ua-ios-pod/issues/13

I am creating a local cocoapod, and the validation step fails, pointing to a xcode build problem.

<code>The following build commands failed:
	CopyStringsFile /var/folders/03/stz43xxd499b61v85gvfc85c0000gs/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods/UrbanAirship_iOS_SDK.framework/UAInteractiveNotifications.strings UrbanAirship-iOS-SDK/Airship/UI/Default/Common/Resources/en.lproj/UAInteractiveNotifications.strings
	CopyStringsFile /var/folders/03/stz43xxd499b61v85gvfc85c0000gs/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods/UrbanAirship_iOS_SDK.framework/UAInteractiveNotifications.strings UrbanAirship-iOS-SDK/Airship/UI/Default/Common/Resources/zh-Hant.lproj/UAInteractiveNotifications.strings
(2 failures)
</code>

I tried 5.1.1 and 6.0.2

**Comment by crow** [comment]
Release 6.1.0 will should fix this issue. Thanks for your patience.
