### ISSUE TITLE
Please enable bitcode

### ISSUE THREAD

**Issue by grosch** [urbanairship/ua-ios-pod#15]
Please provide a version of this POD that has bitcode enabled for iOS 9

**Comment by rlepinski** [comment]
Xcode 7.0 GM just came out, we will be releasing an update with bitcode enabled in the near future.

**Comment by victor** [comment]
bump. We need to upload apps to the app store and iOS 9 support is now required

**Comment by grosch** [comment]
Can we at least get a better ETA than "near future"?  Isn't this just a matter of you rebuilding the library?
