### ISSUE TITLE
Warnings on bitcode version (6.2.1-bitcode)

### ISSUE THREAD

**Issue by stephenwoodford** [urbanairship/ua-ios-pod#18]
Bring this here from the ios-library repo: https://github.com/urbanairship/ios-library/issues/95.

I'm getting a lot of warnings from the UrbanAirship library with bitcode enabled (6.2.1-bitcode) that I do not get if I use the non-bitcode version (6.2.1).

Using Xcode Version 7.0 (7A218)

Here's a gist with the log: https://gist.github.com/stephenwoodford/42c3291092aa7437163b

**Comment by rlepinski** [comment]
Thanks for reporting this. We will try to get it figured out ASAP

**Comment by hcrowell** [comment]
@stephenwoodford Please check out 6.2.2-bitcode which should fix the warnings issue. Thanks for your patience. Closing this issue as resolved.

**Comment by stephenwoodford** [comment]
Seems to have fixed it. Thanks!

**Comment by grosch** [comment]
How are you doing this?  I always get this error:

Pods/UrbanAirship-iOS-SDK/Airship/libUAirship-6.2.2.a(UAWalletAction.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

**Comment by stephenwoodford** [comment]
You have to specify the bitcode version of the library:

In your Podfile: `pod 'UrbanAirship-iOS-SDK', '6.2.1-bitcode'`

Then run `pod update 'UrbanAirship-iOS-SDK'` from Terminal
