### ISSUE TITLE
UAInboxAlertHandler.h using UIAlertView

### ISSUE THREAD

**Issue by grosch** [urbanairship/ua-ios-pod#19]
Please remove deprecated API and replace with UIAlertController instead.

Is the source available somewhere where we can just fix ourself and submit a pull request?

**Comment by rlepinski** [comment]
We still support iOS 6+ and UIAlertController is only in iOS 8+. We will see if we can address it in a future release.

The pod just wraps our library - https://github.com/urbanairship/ios-library, so future tickets like these and any PR can be submitted for that repo.
