### ISSUE TITLE
Unable to import both SwiftyJSON and UrbanAirship with cocoapods

### ISSUE THREAD

**Issue by MavenSean** [urbanairship/ua-ios-pod#21]
So I have a bit of an issue here. I'm using SwiftyJSON which does not appear to work without the use_frameworks option, and I also have need of the UrbanAirship framework as well.

If I disable use_frameworks, I'm able to Import AirshipKit without incident in my AppDelegate. However SwiftyJSON then cacks and I'm not able to use that. The reverse is true however if I enable it.

Has anyone had any luck or found a solution how to have both a dynamic and static library with Cocoapods?

What should my bridging header look like for UrbanAirship -- if I'm even able to use one with use_frameworks enabled?

Current Podfile:
```
platform :ios, '8.0'
use_frameworks!

target 'MyProject' do
    pod 'UrbanAirship-iOS-SDK'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
end
```

**Comment by MavenSean** [comment]
This can be closed.  The documentation should really be updated to reflect that the module is not actually called AirshipKit but rather UrbanAirship_iOS_SDK.

For consistency however, you should try to use the AirshipKit module name to avoid confusion

**Comment by kylefritz** [comment]
@MavenSean how did you get this working? What did you put in your bridging header and (if anything) did you have to import in your swift files to get access to Urban Airship?

in my bridging header, I have:

```objective-c
#import "UrbanAirship_iOS_SDK"
```

in my app delegate, I have:

```swift
import UrbanAirship_iOS_SDK
```

But that's not compiling for me.
