### ISSUE TITLE
Swift import no longer works

### ISSUE THREAD

**Issue by jshier** [urbanairship/ua-ios-pod#22]
Something changed between 6.2.2 and 6.3.0 where I can no longer simply do `import UrbanAirship_iOS_SDK` to import UA. This is with CocoaPods 0.39.0.rc1. What's the new import statement?

**Comment by joshwalker** [comment]
This only happens if you have use_frameworks! enabled in CocoaPods?
The issue is that the pod only includes .h files now, and CocoaPods doesn't create a Module for pods with no 'code'.  You can add 
#import <UrbanAirship-iOS-SDK/AirshipLib.h>
to your bridging header file and then you don't need the import module anymore.

**Comment by jshier** [comment]
Thanks, that sounds right. I'll give it go.

**Comment by crow** [comment]
UrbanAirship_iOS_SDK is now properly named AirshipKit - so the previous import statement workaround is no longer needed.

**Comment by jshier** [comment]
For the record, I had to add `#import <UrbanAirship-iOS-SDK/AirshipLib.h>` to my bridging header and remove all `import` statements from my Swift code.

**Comment by jshier** [comment]
What ever changed here also broke my test target, so I'm going to have to stay at 6.2.2. 

In general I think most CocoaPods users prefer source pods, and obviously CocoaPods works better with them. Plus, building from source directly wouldn't require a separate bit code release.

**Comment by jshier** [comment]
After updating from 7.0.2 to 7.0.4 I needed to once again change how I import UA when using CocoaPods. This time I was able to remove the `#import` from my bridging header and using `import AirshipKit` in the Swift files that needed UA.
