### ISSUE TITLE
Odd constraint warnings on xib's UAMapPresentationViewController.xib,UAPushMoreSettingsView.xib...

### ISSUE THREAD

**Issue by jkunzelman** [urbanairship/ua-ios-pod#23]
Object:   <IBDocumentAutolayoutManager: 0x7fc25376a2d0>
Method:   -invalidateConstraintsForObjectRepresentation:withBlock:
Thread:   <NSThread: 0x7fc250d1a6c0>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
ibtool --reference-external-strings-file --errors --warnings --notices --output-format human-readable-text --compile /Users/club14/Library/Developer/Xcode/DerivedData/Club14-ewidgsyuklrkhkfijulowafbwwbr/Build/Products/Debug-iphonesimulator/CSAA Auto.app/UAMapPresentationViewController.nib /Users/club14/workspace/Club14/Pods/UrbanAirship-iOS-SDK/Airship/UI/Default/Push/Resources/Shared/UAMapPresentationViewController.xib --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
ibtool --reference-external-strings-file --errors --warnings --notices --output-format human-readable-text --compile /Users/club14/Library/Developer/Xcode/DerivedData/Club14-ewidgsyuklrkhkfijulowafbwwbr/Build/Products/Debug-iphonesimulator/CSAA Auto.app/UAPushMoreSettingsView.nib /Users/club14/workspace/Club14/Pods/UrbanAirship-iOS-SDK/Airship/UI/Default/Push/Resources/Shared/UAPushMoreSettingsView.xib --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
ibtool --reference-external-strings-file --errors --warnings --notices --output-format human-readable-text --compile /Users/club14/Library/Developer/Xcode/DerivedData/Club14-ewidgsyuklrkhkfijulowafbwwbr/Build/Products/Debug-iphonesimulator/CSAA Auto.app/UAPushSettingsAddTagViewController.nib /Users/club14/workspace/Club14/Pods/UrbanAirship-iOS-SDK/Airship/UI/Default/Push/Resources/Shared/UAPushSettingsAddTagViewController.xib --sdk /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk
2015-10-09 11:43:08.589 ibtoold[74272:12722565] [MT] DVTAssertions: Warning in /SourceCache/IDEInterfaceBuilder/IDEInterfaceBuilder-7706/InterfaceBuilderKit/AutoLayout/IBDocumentAutolayoutManager.m:536
Details:  We can't open an implicit undo group because there is no undo manager and so the undo group will never get closed and we will be left with a broken arbitration stack. Whoever is invalidating constraints needs to do so in an auto layout safe block.
  0. IDEInterfaceBuilderKit   0x00000001058acc44 -[IBDocumentAutolayoutManager invalidateConstraintsForHierarchyContainingObject:forceInvalidationOfDescendants:reasonBlock:]
  1. IDEInterfaceBuilderKit   0x00000001058ad040 -[IBDocumentAutolayoutManager invalidateConstraintsForHierarchyContainingObject:reasonBlock:]
  2. IDEInterfaceBuilderKit   0x0000000105892ecb -[IBDocument invalidateConstraintsForHierarchyContainingObject:reasonBlock:]
  3. IDEInterfaceBuilderCocoaTouchIntegration 0x000000010bca6ec3 [IBUIView invalidateCachedGeometry]
  4. IDEInterfaceBuilderCocoaTouchIntegration 0x000000010bbff71e [IBUILabel setText:]
  5. Foundation               0x00007fff8e031e7d -[NSObject(NSKeyValueCoding) setValue:forKey:]
  6. Foundation               0x00007fff8e054901 -[NSObject(NSKeyValueCoding) setValue:forKeyPath:]
  7. AppKit                   0x00007fff90e6c5f3 -[NSView setValue:forKeyPath:]
  8. IDEInterfaceBuilderKit   0x000000010588c9df -[IBDocument setNonUndoableValue:forKeyPath:ofMember:inConfiguration:]
  9. IDEInterfaceBuilderKit   0x00000001059f6c71 -[NSObject(IBMemberIntegration) ibSwapInLocalizableStringForDevelopmentString:forKeyPath:inDocument:configuration:context:]
 10. IDEInterfaceBuilderKit   0x00000001059f6fc1 -[NSObject(IBMemberIntegration) ibSwapInLocalizableStringsDuringCompilingInDocument:usingContext:]
 11. IDEInterfaceBuilderKit   0x00000001059f68b9 -[NSObject(IBMemberIntegration) ibSwapInLocalizableStringsIfNeededInDocument:withContext:]
 12. IDEInterfaceBuilderKit   0x000000010585ad16 -[IBDocument willCompileWithContext:]
 13. IDEInterfaceBuilderCocoaTouchIntegration 0x000000010bbf9183 [IBCocoaTouchXIBDocumentCompiler compiledKeyedObjectsDataWithMarshallingContext:archivingContext:]
 14. IDEInterfaceBuilderCocoaTouchIntegration 0x000000010bbfa3b9 IBTargetRuntimesToCompileFor
 15. IDEInterfaceBuilderKit   0x00000001058ba3e9 -[IBDocumentCompiler invokeWithIntermediateDocument:]
 16. IDEInterfaceBuilderKit   0x00000001058ba58d -[IBDocumentCompiler invokeWithIntermediateDocumentOfTargetRuntime:alwaysCopy:block:]
 17. IDEInterfaceBuilderCocoaTouchIntegration 0x000000010bbf9c87 [IBCocoaTouchXIBDocumentCompiler compiledPackageWithOptions:marshallingContext:archivingContext:]
 18. IDEInterfaceBuilderCocoaTouchIntegration 0x000000010bbfa648 [IBCocoaTouchXIBDocumentCompiler compileWithOptions:error:]
 19. IDEInterfaceBuilderKit   0x00000001058ba777 +[IBDocumentCompiler compileContentsOfDocument:options:error:]
 20. IDEInterfaceBuilderKit   0x0000000105875390 __47-[IBDocument compiledPackageWithOptions:error:]_block_invoke
 21. IDEInterfaceBuilderKit   0x00000001058add25 -[IBDocumentAutolayoutManager assertIfArbitrationIsScheduledDuring:]
 22. IDEInterfaceBuilderKit   0x00000001058752e7 -[IBDocument compiledPackageWithOptions:error:]
 23. ???                      0x00000001047fcf0a [IBToolFileManagerDelegate fileManager:shouldCopyItemAtURL:toURL:]
 24. ???                      0x00000001047f9b64 [IBCLIInterfaceBuilderToolPersona invokeArguments:outputDictionary:]
 25. ???                      0x00000001047fc370 [IBCLIInterfaceBuilderToolPersona runSingleInvocation:outputtingToFileHandle:andVerifyingEnvironment:]
 26. ???                      0x0000000104802233 [IBToolFileManagerDelegate fileManager:shouldCopyItemAtURL:toURL:]
 27. ???                      0x00000001048027b0 [IBToolFileManagerDelegate fileManager:shouldCopyItemAtURL:toURL:]
 28. ???                      0x0000000104802683 [IBToolFileManagerDelegate fileManager:shouldCopyItemAtURL:toURL:]
 29. ???                      0x00000001047f166a [IBCLIErrorForwarder forwardErrorOutputToDescriptor:whileInvokingBlock:]
 30. ???                      0x0000000104801e2c [IBToolFileManagerDelegate fileManager:shouldCopyItemAtURL:toURL:]
 31. ???                      0x0000000104801074 [IBToolFileManagerDelegate fileManager:shouldCopyItemAtURL:toURL:]
 32. libdyld.dylib            0x00007fff8dacf5c9 start
 33. ???                      0x0000000000000002 ???

**Comment by rlepinski** [comment]
Our pod no longer ships this class.
