### ISSUE TITLE
Dependencies are wrong (??)

### ISSUE THREAD

**Issue by grosch** [urbanairship/ua-ios-pod#26]
This warning is appearing when I try to archive:

Warning: Multiple build commands for output file /..../Build/Intermediates/ArchiveIntermediates/TeamKnect/IntermediateBuildFilesPath/UninstalledProducts/UrbanAirship_iOS_SDK.framework/en.lproj
Warning: Multiple build commands for output file /..../Build/Intermediates/ArchiveIntermediates/TeamKnect/IntermediateBuildFilesPath/UninstalledProducts/UrbanAirship_iOS_SDK.framework/en.lproj

**Comment by grosch** [comment]
This of course then leads to this build failure:

error: remove /..../Build/Products/Debug-iphoneos/UrbanAirship_iOS_SDK.framework/en.lproj: Directory not empty

**Comment by crow** [comment]
This issue has been resolved. This was due to incorrect directory structuring when installing .lproj files.  Here is the change: https://github.com/CocoaPods/CocoaPods/pull/4408#issue-112143944
