### ISSUE TITLE
latest urban airship doesn't work with latest pods

### ISSUE THREAD

**Issue by mani47** [urbanairship/ua-ios-pod#27]
Build succeeds but when I try to create an Archive, I get this error:

make directory ~/Library/Developer/Xcode/DerivedData/sample-cflavtrhygdlbjaxsmntcfydfeki/Build/Intermediates/ArchiveIntermediates/sample/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AirshipKit.framework/en.lproj: File exists

very frustrating ...

UrbanAirship-iOS-SDK (6.4.0)
pod 0.39.0
Xcode 7.1.1
Swift Project

**Comment by mani47** [comment]
I got the same error when I tried to build the project for running on the device for the first time, problem is there is no en.lproj file in the output directory, So I created en.lproj and error disappeared. but with Build for Archive I can not do this since it deletes all the files first. (I guess it does a clean first)

**Comment by mani47** [comment]
Also I get this warning if that helps:

Warning: Multiple build commands for output file /Users/mani/Library/Developer/Xcode/DerivedData/sample-hboyjcngmjtvrrgkcisbojjpgqrj/Build/Intermediates/ArchiveIntermediates/sample/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/AirshipKit.framework/en.lproj

**Comment by mani47** [comment]
In Copy bundle resources of Urbanairship-iOS-SDK there is three en.lproj folders, removing two of them solved the problem.

**Comment by josephleniston** [comment]
I have the same error. I don't think deleting the language file is the answer. Wouldn't that result in missing translations?

Build works with `pod 'UrbanAirship-iOS-SDK/PushUI` but not with `pod 'UrbanAirship-iOS-SDK/All'`.

**Comment by marc-scig** [comment]
Hey folks,

I believe this is related to a bug in CocoaPods that has recently been addressed: https://github.com/CocoaPods/CocoaPods/pull/4408

 The crux of it is that the scripts responsible for building the framework need to understand how to copy resources from multiple localization bundles. When you're adding stuff manually in Xcode it should collapse UAPushUI.strings and UAInboxUI.strings into a single en.lproj, or just copy the strings files directly. Previously it had been naively copying all lproj bundles into the same framework directory, which means multiple lproj bundles would get overwritten by one another.

While the above PR was merged into master recently, it looks like it didn't make it in time for 0.39. So there are a few potential options here:

* Work with CocoaPods from source off of the current master branch, until the next official release
* Manually edit the copy-files phase of your project to include the correct localizations in Xcode
* Avoid the use of the Push/Inbox sample UI

Regarding that last point, It's worth clarifying that the UI stuff is really intended as sample UI, not a production component of the SDK. The Push UI is mostly just for the PushSample app. The Inbox UI is a starting point for customizing a Message Center. If your app is just doing basic push, you may not need either, in which case the UrbanAirship-iOS-SDK/All is superfluous.

**Comment by waltermvp** [comment]
@marc-scig just tried to install on a new swift project using cocoapods 1 beta 6 and still experience the dame issue

**Comment by waltermvp** [comment]
@marc-scig do you have any specifcs on 
"Manually edit the copy-files phase of your project to include the correct localizations in Xcode"

**Comment by marc-scig** [comment]
@waltermvp what version of the SDK are you using? Urban Airship SDK 7+ uses a resource bundle for localized strings, which might avoid the problem altogether.

**Comment by marc-scig** [comment]
Regarding the copy-files phase, if you click your app's project in the left pane of Xcode, you should see a "Build Phases" tab in the middle pane. Within that pane is "Copy Bundle Resources", which is the phase where Xcode copies stuff like images, localizations, xibs/storyboards, etc into the app bundle. 

What you *should* see here are the .strings files, with a disclosure arrow for any additional localizations. If instead you see multiple en.lproj folders cocoapods probably copied them over incorrectly.  You can delete those references in "Copy Bundle Resources" and drag the .strings files over manually, which should do the trick.

**Comment by waltermvp** [comment]
@marc-scig  im using the latest, version of the UA SDK. Its a mixed objc swift project FYI. Also thanks for the quick response

**Comment by marc-scig** [comment]
np, glad to help as best I can. What's the specific error you're seeing?

**Comment by waltermvp** [comment]
"No such module" for both

`import UAirship` & `import AirshipKit`

Im using cocoapods .39 , xcode 7.3 and this occurs in a swift file. Im currently using `#import <UrbanAirship-iOS-SDK/AirshipLib.h>` in a objc file and it works fine.

**Comment by waltermvp** [comment]
@marc-scig please let me know if there is any other information i can provide to assist, and once again thank you

**Comment by marc-scig** [comment]
Hey @waltermvp, thanks for the info and we're in the midst of fixing it. It looks as though we neglected to add AirshipKit to the repo, and the spec needs a few tweaks as well. Should be out soon, we'll let you know when there's something available.

**Comment by waltermvp** [comment]
@marc-scig thanks for the reply. Very much appreciated. Any ETA?

**Comment by marc-scig** [comment]
@waltermvp should be up sometime today, or tomorrow at the latest. We're putting together a 7.0.3 patch release with a few other minor updates.

**Comment by waltermvp** [comment]
@marc-scig thats great news!!! thank you for your support. ill be sure to mention this to the decision makers at my company, this reflects well on Urban Airship.

**Comment by marc-scig** [comment]
@waltermvp thank you for the kind words! There's a 7.0.3.rc1 spec up now. Give that a try, and if it solves your problem then we'll promote it to an official 7.0.3 release.

**Comment by waltermvp** [comment]
Problem Solved on my end :+1:

**Comment by waltermvp** [comment]
@marc-scig  Sorry for the premature response
Im getting a crash in   ` func application(application: UIApplication, didFinishLaunchingWithOptions launchOptions: [NSObject: AnyObject]?) -> Bool`.

Specifically, the second line ()

```swift
        UAirship.takeOff()
        UAirship.push().userPushNotificationsEnabled = true
        UAirship.push().pushNotificationDelegate = self;
```

FYI this is the only code in that method and i go have the airship plist in the bundle

**Comment by rlepinski** [comment]
@waltermvp so if `UAirship.takeOff()` fails, then the instances will be null. Do you have any helpful log messages?

**Comment by waltermvp** [comment]
Cant get a actual crash in the console despite the fact that i keep skipping over the exception breakpoints but here is a screen shot. "fatalErroMessage"
![issue](https://cloud.githubusercontent.com/assets/1158238/14183317/b4e3c166-f73d-11e5-86bc-764135586317.png)

**Comment by waltermvp** [comment]
`UAirship.takeOff()` on its own work fine, its the second line that causes the issue

**Comment by rlepinski** [comment]
Yeah, so I think `UAirship.takeOff()` might be failing, then the second line will crash because `UAirship.push()` will be nil. Does the console logs say anything about takeoff failing?

**Comment by waltermvp** [comment]
nope is there some loggin i can enable?

**Comment by waltermvp** [comment]
`2016-03-31 12:44:48.263 CheckedUpUpdater[725:154141] [T] +[UAConfig configWithContentsOfFile:] [Line 174] Config options: {
    detectProvisioningMode = 1;
    developmentAppKey = "M7-uXM3gTgGruOY90fRiog";
    developmentAppSecret = "lurfUBZIT32doMi9r-zz1w";
    productionAppKey = "Your Production App Key";
    productionAppSecret = "Your Production App Secret";
}
2016-03-31 12:44:48.265 CheckedUpUpdater[725:154141] [T] +[UAConfig isProductionProvisioningProfile:] [Line 340] Profile path: /var/containers/Bundle/Application/FB2EFA1F-B9E6-4ED0-8851-E414AA2BA2FF/CheckedUpUpdater.app/embedded.mobileprovision
2016-03-31 12:44:48.267 CheckedUpUpdater[725:154141] [D] +[UAConfig isProductionProvisioningProfile:] [Line 364] Debug provisioning profile. Uses the APNS Sandbox Servers.
2016-03-31 12:44:48.268 CheckedUpUpdater[725:154141] [D] +[UAConfig isProductionProvisioningProfile:] [Line 375] APS Environment set to (null)
2016-03-31 12:44:48.268 CheckedUpUpdater[725:154141] [E] +[UAConfig isProductionProvisioningProfile:] [Line 382] aps-environment value is not set. If this is not a simulator, ensure that the app is properly provisioned for push
2016-03-31 12:44:48.281 CheckedUpUpdater[725:154141] [E] -[UAConfig validate] [Line 244] Current App Key (Your Production App Key) is not valid.
2016-03-31 12:44:48.282 CheckedUpUpdater[725:154141] [E] -[UAConfig validate] [Line 249] Current App Secret (Your Production App Secret) is not valid.
2016-03-31 12:44:48.282 CheckedUpUpdater[725:154141] Urban Airship Implementation Error - The UAConfig is invalid, no application credentials were specified at runtime.
fatal error: unexpectedly found nil while unwrapping an Optional value
(lldb) `

**Comment by waltermvp** [comment]
I have ensured that dev keys are there and the scheme is running in debug

**Comment by rlepinski** [comment]
Ok, can you try setting inProduction to false/NO in the config?

**Comment by waltermvp** [comment]
there is a key in the plist `detectProvisioningMode` is that what i should set to no?

**Comment by waltermvp** [comment]
Just tried that and it works :)

**Comment by rlepinski** [comment]
`detectProvisioningMode` lets UA figure out what config to use. You can also manually set it with `inProduction` = NO/YES.

**Comment by rlepinski** [comment]
The good news is the podspec works :smile:. Bad news is it looks like the SDK is failing to detect provision mode correctly for your setup. We will look into it and try to address it in a future release. For now you can use the inProduction flag to manually set it. Just make sure you set it to true before releasing.

**Comment by waltermvp** [comment]
@rlepinski that works thanks!
