### ISSUE TITLE
Impossible compile project missing Lib

### ISSUE THREAD

**Issue by Douvi** [urbanairship/ua-ios-pod#33]
After downloaded from pod, I try to compile and I got this error :

`UAWalletAction.h:27:9: 'Passkit/Passkit.h' file not found`

**Comment by Douvi** [comment]
So no body have this issue ?

**Comment by crow** [comment]
I am unable to reproduce this on my end. Please provide your steps to reproduce this using the sample project.

**Comment by crow** [comment]
Issue is stale, closing for now
