### ISSUE TITLE
Version 8.0.0 is Broken

### ISSUE THREAD

**Issue by xlsmearlx** [urbanairship/ua-ios-pod#40]
Can't compile project after update to version 8.0.0

.../Pods/Headers/Public/UrbanAirship-iOS-SDK/UAAppIntegration.h:27: 'UserNotifications/UserNotifications.h' file not found

**Comment by rlepinski** [comment]
What xcode are you using? 8.0.0 requires Xcode 8

**Comment by crow** [comment]
closing until we get more info
