### ISSUE TITLE
6.0.0 doesn't register

### ISSUE THREAD

**Issue by grosch** [urbanairship/ua-ios-pod#8]
I just upgrade to this newer 6.0.0 version and swapped to calling UAirship.push() like the compiler told me to based on your warnings.   Now that I've done that, application(_:didRegisterForRemoteNotificationsWithDeviceToken) is no longer called.

**Comment by grosch** [comment]
I just set the logging level to .Trace and the only message that appears in the Channel ID.  Then I set the registration delegate.  That calls registrationSucceededForChannelID and passes in that channel ID, but passes nil for the deviceToken.  Verified that the phone settings have all notifications for this app turned on.

**Comment by crow** [comment]
Are you currently setting [UAirship push].userPushNotificationsEnabled to YES?
