### ISSUE TITLE
Example is REALLY old

### ISSUE THREAD

**Issue by grosch** [urbanairship/ua-ios-pod#9]
It's not using the actual API.  Please update.

**Comment by crow** [comment]
Please elaborate.

**Comment by grosch** [comment]
Well, for starters, it's not using the actual API.  It's using deprecated items.  You're supposed to be using UAirship.push now, for example.

**Comment by crow** [comment]
The PodSample will be updated in the 6.1.0 release.  Thanks for your patience.
